"""Generate the local TypeScript dataset from a verified pinned compiler build."""
import base64
import hashlib
import json
from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit('Usage: generate-timezone-data.py compiled-build-directory NEW-output.ts')
base, output = map(lambda value: Path(value).resolve(), sys.argv[1:])
license_output = output.parent / 'timezone-LICENSE.txt'
if output == license_output or output.exists() or license_output.exists():
    raise SystemExit('Output and adjacent license must be new files; use a fresh scratch directory.')
manifest = json.loads((base / 'build-manifest.json').read_text())
if manifest.get('exitCode') != 0 or manifest.get('revision') != '2026d' or manifest.get('format') != 'slim' or not manifest.get('compilerBuildManifestSha256'):
    raise SystemExit('A pinned-source slim compiler build is required.')
compiler_manifest_bytes = (Path(manifest['compiler']).parent / 'compiler-manifest.json').read_bytes()
if hashlib.sha256(compiler_manifest_bytes).hexdigest() != manifest['compilerBuildManifestSha256']:
    raise SystemExit('Compiler manifest changed.')
compiler = json.loads(compiler_manifest_bytes)
if compiler.get('exitCode') != 0 or compiler.get('compilerVersion') != 'zic (tzcode) 2026d':
    raise SystemExit('A successful pinned compiler build is required.')
compiler_hash = hashlib.sha256(Path(manifest['compiler']).read_bytes()).hexdigest()
if compiler_hash != compiler.get('compilerSha256') or compiler_hash != manifest.get('compilerSha256'):
    raise SystemExit('Compiler bytes differ from the build manifests.')
license_bytes = (base / 'source' / 'LICENSE').read_bytes()
if hashlib.sha256(license_bytes).hexdigest() != manifest.get('sourceHashes', {}).get('LICENSE'):
    raise SystemExit('Source license differs from the build manifest.')
if not manifest.get('files'):
    raise SystemExit('The compiled zone inventory is empty.')
if compiler['archives'] != {
    'tzcode2026d.tar.gz': '2f5c9f7fe29e6b8cb863583667884b8ce17b0a485355a054b591c6bdfcd81791',
    'tzdata2026d.tar.gz': '0cb2aa8e333c3dc049badc42a0c61f21987b8cd44e107fa900bad764aacc7767',
}:
    raise SystemExit('Unexpected compiler source archives.')
aliases, files, indices = {}, [], {}
for zone, expected in sorted(manifest['files'].items()):
    data = (base / 'compiled' / zone).read_bytes()
    if hashlib.sha256(data).hexdigest() != expected:
        raise SystemExit('Compiled file changed: ' + zone)
    if expected not in indices:
        indices[expected] = len(files)
        files.append(base64.b64encode(data).decode('ascii'))
    aliases[zone] = indices[expected]
payload = {'aliases': aliases, 'files': files}
payload_hash = hashlib.sha256(json.dumps(payload, separators=(',', ':')).encode()).hexdigest()
source_text = ('// Generated by comparison/calendar/generate-timezone-data.py; do not edit.\n'
                  '// IANA 2026d; license in timezone-LICENSE.txt.\n'
                  f'// Data payload SHA-256: {payload_hash}\n'
                  'export const TIMEZONE_DATA_VERSION = "2026d";\n'
                  'export const timezoneData: { aliases: Record<string, number>; files: string[] } = '
                  + json.dumps(payload, indent=2) + ';\n')
with output.open('x') as target:
    target.write(source_text)
with license_output.open('xb') as target:
    target.write(license_bytes)
print(json.dumps({'zones': len(aliases), 'uniqueFiles': len(files), 'payloadSha256': payload_hash}))
