"""Check bundled literals against a retained compiled build without importing JS."""
import base64
import hashlib
import io
import json
from pathlib import Path
import re
import sys
from zoneinfo import ZoneInfo


def digest(data):
    return hashlib.sha256(data).hexdigest()


def verify(source, build):
    text = source.read_text()
    # Accept only this generated declaration and inert JSON-shaped literals.
    header, body = text.split('export const timezoneData: { aliases: Record<string, number>; files: string[] } = ', 1)
    match = re.fullmatch(
        r'// Generated by comparison/calendar/generate-timezone-data.py; do not edit.\n'
        r'// IANA 2026d; license in timezone-LICENSE.txt.\n'
        r'// Data payload SHA-256: ([a-f0-9]{64})\n'
        r'export const TIMEZONE_DATA_VERSION = "2026d";\n', header)
    if not match:
        raise ValueError('Unexpected generated header')
    lines = [line.strip() for line in body.splitlines()]
    split = lines.index('files: [')
    if lines[:2] != ['{', 'aliases: {'] or lines[split - 1] != '},' or lines[-2:] != ['],', '};']:
        raise ValueError('Unexpected literal structure')
    aliases, files = {}, []
    for line in lines[2:split - 1]:
        entry = re.fullmatch(r'(?:"([A-Za-z0-9_+./-]+)"|([A-Za-z_$][A-Za-z0-9_$]*)): (\d+),', line)
        if not entry:
            raise ValueError('Expected zone/index literal')
        key = entry[1] or entry[2]
        if key in aliases:
            raise ValueError('Duplicate zone: ' + key)
        aliases[key] = int(entry[3])
    for line in lines[split + 1:-2]:
        entry = re.fullmatch(r'"([A-Za-z0-9+/=]+)",', line)
        if not entry:
            raise ValueError('Expected base64 literal')
        files.append(entry[1])
    payload = {'aliases': aliases, 'files': files}
    payload_hash = digest(json.dumps(payload, separators=(',', ':')).encode())
    if payload_hash != match[1]:
        raise ValueError('Payload differs from declared digest')
    decoded = [base64.b64decode(item, validate=True) for item in files]
    for data in decoded:
        ZoneInfo.from_file(io.BytesIO(data))
    manifest_bytes = (build / 'build-manifest.json').read_bytes()
    manifest = json.loads(manifest_bytes)
    if manifest['revision'] != '2026d' or manifest['format'] != 'slim' or manifest['exitCode'] != 0:
        raise ValueError('Expected successful 2026d slim build')
    if set(aliases) != set(manifest['files']) or set(aliases.values()) != set(range(len(files))):
        raise ValueError('Incomplete zone or payload coverage')
    for zone, index in aliases.items():
        if '..' in zone.split('/') or zone.startswith('/'):
            raise ValueError('Invalid zone path')
        data = decoded[index]
        if digest(data) != manifest['files'][zone] or data != (build / 'compiled' / zone).read_bytes():
            raise ValueError('Compiled zone differs: ' + zone)
    if (source.parent / 'timezone-LICENSE.txt').read_bytes() != (build / 'source' / 'LICENSE').read_bytes():
        raise ValueError('License differs')
    return {'zones': len(aliases), 'uniqueFiles': len(files), 'payloadSha256': payload_hash,
            'sourceSha256': digest(source.read_bytes()), 'buildManifestSha256': digest(manifest_bytes),
            'checks': ['inert literals', 'declared payload digest', 'all base64 decoded',
                       'all unique files read by Python ZoneInfo', 'all compiled zone bytes', 'license'],
            'limitations': ['Retained-build identity, not independent upstream authentication or hermetic compiler proof.',
                            'Reader acceptance does not prove every calendar value or client import.']}


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit('Usage: verify-timezone-data.py source.ts compiled-build-directory')
    print(json.dumps(verify(*(Path(value).resolve() for value in sys.argv[1:])), indent=2))
